# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nidevice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nidevice.proto',
  package='nidevice_grpc',
  syntax='proto3',
  serialized_options=b'\n\022com.ni.grpc.deviceB\010NiDeviceP\001\252\002\037NationalInstruments.Grpc.Device',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0enidevice.proto\x12\rnidevice_grpc\"2\n\x0fNIComplexNumber\x12\x0c\n\x04real\x18\x01 \x01(\x01\x12\x11\n\timaginary\x18\x02 \x01(\x01\"5\n\x12NIComplexNumberF32\x12\x0c\n\x04real\x18\x01 \x01(\x02\x12\x11\n\timaginary\x18\x02 \x01(\x02\"/\n\x0cNIComplexI16\x12\x0c\n\x04real\x18\x01 \x01(\x11\x12\x11\n\timaginary\x18\x02 \x01(\x11\"r\n\x0fSmtSpectrumInfo\x12\x15\n\rspectrum_type\x18\x01 \x01(\r\x12\x11\n\tlinear_db\x18\x02 \x01(\r\x12\x0e\n\x06window\x18\x03 \x01(\r\x12\x13\n\x0bwindow_size\x18\x04 \x01(\x11\x12\x10\n\x08\x66\x66t_size\x18\x05 \x01(\x11\x42\x42\n\x12\x63om.ni.grpc.deviceB\x08NiDeviceP\x01\xaa\x02\x1fNationalInstruments.Grpc.Deviceb\x06proto3'
)




_NICOMPLEXNUMBER = _descriptor.Descriptor(
  name='NIComplexNumber',
  full_name='nidevice_grpc.NIComplexNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='nidevice_grpc.NIComplexNumber.real', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imaginary', full_name='nidevice_grpc.NIComplexNumber.imaginary', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=83,
)


_NICOMPLEXNUMBERF32 = _descriptor.Descriptor(
  name='NIComplexNumberF32',
  full_name='nidevice_grpc.NIComplexNumberF32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='nidevice_grpc.NIComplexNumberF32.real', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imaginary', full_name='nidevice_grpc.NIComplexNumberF32.imaginary', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=138,
)


_NICOMPLEXI16 = _descriptor.Descriptor(
  name='NIComplexI16',
  full_name='nidevice_grpc.NIComplexI16',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='nidevice_grpc.NIComplexI16.real', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imaginary', full_name='nidevice_grpc.NIComplexI16.imaginary', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=187,
)


_SMTSPECTRUMINFO = _descriptor.Descriptor(
  name='SmtSpectrumInfo',
  full_name='nidevice_grpc.SmtSpectrumInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spectrum_type', full_name='nidevice_grpc.SmtSpectrumInfo.spectrum_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_db', full_name='nidevice_grpc.SmtSpectrumInfo.linear_db', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='window', full_name='nidevice_grpc.SmtSpectrumInfo.window', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='window_size', full_name='nidevice_grpc.SmtSpectrumInfo.window_size', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fft_size', full_name='nidevice_grpc.SmtSpectrumInfo.fft_size', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=303,
)

DESCRIPTOR.message_types_by_name['NIComplexNumber'] = _NICOMPLEXNUMBER
DESCRIPTOR.message_types_by_name['NIComplexNumberF32'] = _NICOMPLEXNUMBERF32
DESCRIPTOR.message_types_by_name['NIComplexI16'] = _NICOMPLEXI16
DESCRIPTOR.message_types_by_name['SmtSpectrumInfo'] = _SMTSPECTRUMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NIComplexNumber = _reflection.GeneratedProtocolMessageType('NIComplexNumber', (_message.Message,), {
  'DESCRIPTOR' : _NICOMPLEXNUMBER,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.NIComplexNumber)
  })
_sym_db.RegisterMessage(NIComplexNumber)

NIComplexNumberF32 = _reflection.GeneratedProtocolMessageType('NIComplexNumberF32', (_message.Message,), {
  'DESCRIPTOR' : _NICOMPLEXNUMBERF32,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.NIComplexNumberF32)
  })
_sym_db.RegisterMessage(NIComplexNumberF32)

NIComplexI16 = _reflection.GeneratedProtocolMessageType('NIComplexI16', (_message.Message,), {
  'DESCRIPTOR' : _NICOMPLEXI16,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.NIComplexI16)
  })
_sym_db.RegisterMessage(NIComplexI16)

SmtSpectrumInfo = _reflection.GeneratedProtocolMessageType('SmtSpectrumInfo', (_message.Message,), {
  'DESCRIPTOR' : _SMTSPECTRUMINFO,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.SmtSpectrumInfo)
  })
_sym_db.RegisterMessage(SmtSpectrumInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
